name: Android CI

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

  lint:
    name: Lint Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ktlint
        run: bash ./gradlew :app:ktlintDebugCheck
      - name: Run lint
        run: bash ./gradlew :app:lintDebug
