name: Android CI

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  test:
    name: Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Access API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./local.properties
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  lint:
    name: Lint Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Access API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./local.properties
      - name: Run ktlint
        run: bash ./gradlew :app:ktlintDebugCheck
      - name: Run lint
        run: bash ./gradlew :app:lintDebug
